package com.example.preprocessing.enums;

public enum EConfig {
	PATH_RESOURCE_SOURCE("PATH_RESOURCE_SOURCE"),
	PATH_RESOURCE_RESULT("PATH_RESOURCE_RESULT"),
	PATH_RESOURCE_POSITIVE("PATH_RESOURCE_POSITIVE"),
	PATH_RESOURCE_NEGATIVE("PATH_RESOURCE_NEGATIVE"),
	PATH_RESOURCE_WORD("PATH_RESOURCE_WORD"),
	
	RESULT_RELATION("RESULT_RELATION"),
	RESULT_ATTRIBRUTE_UNSUPERVISED("RESULT_ATTRIBRUTE_UNSUPERVISED"),
	RESULT_ATTRIBRUTE_SUPERVISED("RESULT_ATTRIBRUTE_SUPERVISED"),
	RESULT_POSITIVE_SUPERVISED("RESULT_POSITIVE_SUPERVISED"),
	RESULT_NEGATIVE_SUPERVISED("RESULT_NEGATIVE_SUPERVISED"),
	RESULT_REQUIRMENT_KEY("RESULT_REQUIRMENT_KEY");
	
	private String val;
	EConfig(String eConfig){
		this.val = eConfig;
	}
	public String getText() {
		return this.val;
	}
}
